require 'rake'

macosx = (ENV_JAVA['os.name'] == 'Mac OS X') rescue nil

task :all =>   [:compile, :jarify, :run]
task :build => [:compile, :jarify]

task :compile do
  sh 'jruby -S jrubyc org/qtjruby/boot.rb'
end

task :jarify do
  sh 'jar cfm qtjruby-complete-0.2.0.jar manifest .'
end

task :run do
  sh "java #{macosx ? '-XstartOnFirstThread' : nil} -jar qtjruby-complete-0.2.0.jar #{ARGV.pop}"
end